backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts_list"
    label: "ዜናዎችን መለጠፊያ (News Posts)"
    files:
      - file: "news.json"
        name: "news_data"
        label: "የዜና ዝርዝሮች (All News)"
        fields:
          - name: "posts"
            label: "የዜናዎች ዝርዝር"
            widget: "list"
            fields:
              - { label: "አርዕስት (Title)", name: "title", widget: "string" }
              - { label: "ምድብ (Category)", name: "category", widget: "select", options: ["ፖለቲካ", "ኢኮኖሚ", "ቴክኖሎጂ", "ስፖርት", "መዝናኛ"] }
              - { label: "ቀን (Date)", name: "date", widget: "string" }
              - { label: "ዘጋቢ ስም (Author)", name: "author", widget: "string" }
              - { label: "ምስል (Image)", name: "image", widget: "image" }
              - { label: "አጭር መግለጫ (Summary)", name: "description", widget: "text" }
              - { label: "ሙሉ ዜና (Body)", name: "body", widget: "text" }
